### ISSUE TITLE
Colocar botón para mostrar contraseña

### ISSUE THREAD

**Issue by geronm12** [N4choCM/rollingEats#57]
### SITUACTION ACTUAL
Acceder al sitio web y dirigirse a la solapa de registrarse, llenar el campo de contraseña

### RESULTADO OBTENIDO
El txt de la contraseña no me ofrece la posbilidad de revisar si estoy colocando bien la misma

### RESULTADO ESPERADO
El input debería ofrecerle al usuario una forma que le permite saber si las acciones que realiza son correctas

**Adjunto Pruebas**

![image](https://github.com/N4choCM/rollingEats/assets/44532299/2e764151-6e01-4084-97ac-5d52d07079f9)

**Comment by N4choCM** [comment]
Done
