### ISSUE TITLE
Modificar Imagen de Hamburguesa

### ISSUE THREAD

**Issue by geronm12** [N4choCM/rollingEats#58]
### SITUACION ACTUAL
Ingresar a la web con un usuario previamente registrado, en la pantalla principal se podrá observar que en el carousel una de las imagenes no se muestra correctamente

### RESULTADO OBTENIDO
La imagen de la hamburguesa no se renderiza

### RESULTADO ESPERADO
Las imagenes deben cargarse correctamente y nuestra consola tiene que permanecer siempre lo más impecable posible

**Adunto Pruebas**

![image](https://github.com/N4choCM/rollingEats/assets/44532299/acf16ac3-b89c-4bee-919f-d24ddc9e24dd)

**Comment by N4choCM** [comment]
Me sorprende mucho porque lleva un mes funcionando y, de hecho, esta semana ha funcionado todos los días, pero ya cambié la foto y la consola está limpia.
