### ISSUE TITLE
En la solapa de pedidos si no existe ningún pedido aparece un spinner cargando

### ISSUE THREAD

**Issue by geronm12** [N4choCM/rollingEats#61]
### SITUACION ACTUAL
Ingresar al sitio con un usuario registrado, sin agregar ningún pedido (o si existe alguno eliminarlo).

### RESULTADO OBTENIDO
El spinner queda cargando y al salir del link/ volver a entrar el spinner continúa.

### RESULTADO ESPERADO
Si no tenemos ningún item en el array debemos mostrar un label y esconder el spinner

**Adjunto Pruebas**

https://github.com/N4choCM/rollingEats/assets/44532299/51520eb6-fac1-4ea3-a9d2-4ecce4243fef

https://github.com/N4choCM/rollingEats/assets/44532299/25e0cae9-f1b3-41bb-b102-2ceae9fceeeb

**Comment by N4choCM** [comment]
Done.
