### ISSUE TITLE
No mostrar Ids

### ISSUE THREAD

**Issue by geronm12** [N4choCM/rollingEats#62]
### SITUACION ACTUAL
Ingresar al sitio web, hacer click en agregar un pedido, acceder a la solapa de pedidos y presionar el botón de eliminar

### RESULTADO OBTENIDO
El pop up muestra el id del objeto a eliminar

### RESULTADO ESPERADO
No deberíamos mostrar el id, es conveniente modificarlo por el nombre del menú en este caso. 
EJ: ¿Está seguro de que quiere inactivar el pedido Sabores del caribe?

**Adjunto Pruebas**
![image](https://github.com/N4choCM/rollingEats/assets/44532299/16939e33-0e95-4bd6-8c6c-af85d54b87e2)

Nota extra: El usuario no debería tener noción del id puesto a que no es desarrollador, el id es más para nosotros, se podría crear un número de pedido como propiedad en el documento de la base de datos para poder identificarlos sin necesidad de usar el id o se podría colocar en el label el nombre del menú

**Comment by N4choCM** [comment]
Solved
